/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package moduledefault.clustering.view.frames;

import java.io.IOException;
import java.io.Serializable;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextField;
import moduledefault.clustering.uteis.ArquivoFormigas;
import moduledefault.clustering.uteis.Arquivos;

/**
 *
 * @author Mateus
 */
public class JFrameFormigas extends javax.swing.JFrame {

    /**
     * Creates new form JFrameFormigas
     */
    public JFrameFormigas() {
        initComponents();
        setSigma(Integer.parseInt(this.textSigma.getText()));
        setSigmaMaximo(Integer.parseInt(this.textSigmaMaximo.getText()));
        setSigmaMinimo(Integer.parseInt(this.textControleSigma.getText()));
        setSigmaControle(Integer.parseInt(this.textControleSigma.getText()));
        setAlfa(Double.parseDouble(this.textAlfa.getText()));
        setAlfaMaximo(Double.parseDouble(this.textAlfaMaximo.getText()));
        setIteracoes(Integer.parseInt(this.textIteracoes.getText()));
        setAlfaMinimo(Double.parseDouble(this.textAlfaMinimo.getText()));
        setAlfaControle(Double.parseDouble(this.textControleAlfa.getText()));
        setFase(Double.parseDouble(this.textFase.getText()));
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        abrir.setEnabled(true);
        salvar.setEnabled(true);
    }
    int sigma;
    int sigmaMaximo;
    int sigmaMinimo;
    int sigmaControle;
    int iteracoes;
    double alfa;
    double alfaMaximo;
    double alfaMinimo;
    double alfaControle;
    double fase;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        textSigma = new javax.swing.JTextField();
        textSigmaMaximo = new javax.swing.JTextField();
        textControleSigma = new javax.swing.JTextField();
        textAlfa = new javax.swing.JTextField();
        textAlfaMaximo = new javax.swing.JTextField();
        textAlfaMinimo = new javax.swing.JTextField();
        textControleAlfa = new javax.swing.JTextField();
        textFase = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        textIteracoes = new javax.swing.JTextField();
        abrir = new javax.swing.JButton();
        salvar = new javax.swing.JButton();
        buttonOK = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "YADMT.Clustering.AC"));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setName(""); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Sobre"));

        jLabel10.setText("Agrupamento de Dados Baseado em Colônia de Formigas");

        jButton1.setText("Sobre");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Configurações"));

        jLabel1.setText("raio inicial");

        jLabel2.setText("raio max");

        jLabel4.setText("raio controle(min p/ 2° fase)");

        jLabel5.setText("alfa");

        jLabel6.setText("alfa max");

        jLabel7.setText("alfa min");

        jLabel8.setText("alfa controle(min p/ 2° fase)");

        jLabel9.setText("Fase:");

        textSigma.setText("1");

        textSigmaMaximo.setText("4");

        textControleSigma.setText("1");

        textAlfa.setText("1");

        textAlfaMaximo.setText("1");

        textAlfaMinimo.setText("0.8");

        textControleAlfa.setText("0.8");

        textFase.setText("20");
        textFase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFaseActionPerformed(evt);
            }
        });

        jLabel11.setText("iterações");

        textIteracoes.setText("10000");
        textIteracoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textIteracoesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel11)
                                .addComponent(jLabel1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textSigma)
                            .addComponent(textSigmaMaximo)
                            .addComponent(textControleSigma)
                            .addComponent(textFase)
                            .addComponent(textIteracoes)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textAlfa)
                            .addComponent(textAlfaMaximo)
                            .addComponent(textAlfaMinimo, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                            .addComponent(textControleAlfa))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(textIteracoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textSigma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textSigmaMaximo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(textControleSigma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(textAlfa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(textAlfaMaximo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(textAlfaMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textControleAlfa, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(textFase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        abrir.setText("Abrir");
        abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirActionPerformed(evt);
            }
        });

        salvar.setText("Salvar");
        salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarActionPerformed(evt);
            }
        });

        buttonOK.setText("OK");
        buttonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOKActionPerformed(evt);
            }
        });

        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(abrir, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonOK, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(abrir)
                    .addComponent(salvar)
                    .addComponent(buttonOK)
                    .addComponent(cancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel1.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOKActionPerformed
        setValores();
    }//GEN-LAST:event_buttonOKActionPerformed

    private void textFaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFaseActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_cancelarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFrameSobreACO aco = new JFrameSobreACO(this.getLocation(), this.getWidth());
        aco.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarActionPerformed
        setValores();
        ArquivoFormigas aF = new ArquivoFormigas(sigma, sigmaMaximo, sigmaMinimo, sigmaControle, alfa, alfaMaximo, alfaMinimo, alfaControle, fase);
        Arquivos fileF = new Arquivos();
        fileF.salvarFormigas(aF);
    }//GEN-LAST:event_salvarActionPerformed

    private void abrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirActionPerformed
        Arquivos fileF = new Arquivos();
        try {
            ArquivoFormigas aF = fileF.abrirFormigas();
            setSigma(aF.getSigma());
            setSigmaMaximo(aF.getSigmaMaximo());
            setSigmaMinimo(aF.getSigmaMinimo());
            setSigmaControle(aF.getSigmaControle());
            setAlfa(aF.getAlfa());
            setAlfaMaximo(aF.getAlfaMaximo());
            setAlfaMinimo(aF.getAlfaMinimo());
            setAlfaControle(aF.getAlfaControle());
            setFase(aF.getFase());
            textSigma.setText(String.valueOf(getSigma()));
            textSigmaMaximo.setText(String.valueOf(getSigmaMaximo()));
            //textSigmaMinimo.setText(String.valueOf(getSigmaMinimo()));
            textControleSigma.setText(String.valueOf(getSigmaControle()));
            textAlfa.setText(String.valueOf(getAlfa()));
            textAlfaMaximo.setText(String.valueOf(getAlfaMaximo()));
            textAlfaMinimo.setText(String.valueOf(getAlfaMinimo()));
            textControleAlfa.setText(String.valueOf(getAlfaControle()));
            textFase.setText(String.valueOf(getFase()));
        } catch (IOException ex) {
            Logger.getLogger(JFrameFormigas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_abrirActionPerformed

    private void textIteracoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textIteracoesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textIteracoesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameFormigas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameFormigas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameFormigas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameFormigas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameFormigas().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton abrir;
    private javax.swing.JButton buttonOK;
    private javax.swing.JButton cancelar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton salvar;
    private javax.swing.JTextField textAlfa;
    private javax.swing.JTextField textAlfaMaximo;
    private javax.swing.JTextField textAlfaMinimo;
    private javax.swing.JTextField textControleAlfa;
    private javax.swing.JTextField textControleSigma;
    private javax.swing.JTextField textFase;
    private javax.swing.JTextField textIteracoes;
    private javax.swing.JTextField textSigma;
    private javax.swing.JTextField textSigmaMaximo;
    // End of variables declaration//GEN-END:variables

    
    public int getSigma() {
        return sigma;
    }
    
    public int getIteracoes() {
        return iteracoes;
    }

    public void setIteracoes(int iteracoes) {
        this.iteracoes = iteracoes;
    }

    public void setSigma(int sigma) {
        this.sigma = sigma;
    }

    public int getSigmaMaximo() {
        return sigmaMaximo;
    }

    public void setSigmaMaximo(int sigmaMaximo) {
        this.sigmaMaximo = sigmaMaximo;
    }

    public int getSigmaMinimo() {
        return sigmaMinimo;
    }

    public void setSigmaMinimo(int sigmaMinimo) {
        this.sigmaMinimo = sigmaMinimo;
    }

    public double getAlfa() {
        return alfa;
    }

    public void setAlfa(double alfa) {
        this.alfa = alfa;
    }

    public double getAlfaMaximo() {
        return alfaMaximo;
    }

    public void setAlfaMaximo(double alfaMaximo) {
        this.alfaMaximo = alfaMaximo;
    }

    public double getAlfaMinimo() {
        return alfaMinimo;
    }

    public void setAlfaMinimo(double alfaMinimo) {
        this.alfaMinimo = alfaMinimo;
    }

    public double getAlfaControle() {
        return alfaControle;
    }

    public void setAlfaControle(double alfaControle) {
        this.alfaControle = alfaControle;
    }

    public double getFase() {
        return fase;
    }

    public void setFase(double fase) {
        this.fase = fase;
    }

    public int getSigmaControle() {
        return sigmaControle;
    }

    public void setSigmaControle(int sigmaControle) {
        this.sigmaControle = sigmaControle;
    }

    private void setValores() {
        setSigma(Integer.parseInt(this.textSigma.getText()));
        setSigmaMaximo(Integer.parseInt(this.textSigmaMaximo.getText()));
        setSigmaMinimo(Integer.parseInt(this.textControleSigma.getText()));
        setSigmaControle(Integer.parseInt(this.textControleSigma.getText()));
        setAlfa(Double.parseDouble(this.textAlfa.getText()));
        setIteracoes(Integer.parseInt(this.textIteracoes.getText()));
        setAlfaMaximo(Double.parseDouble(this.textAlfaMaximo.getText())); 
        setAlfaMinimo(Double.parseDouble(this.textAlfaMinimo.getText()));
        setAlfaControle(Double.parseDouble(this.textControleAlfa.getText()));
        setFase(Double.parseDouble(this.textFase.getText()));
        this.setVisible(false);
    }
}
